//! Test suite for the Web and headless browsers.

#![cfg(target_arch = "wasm32")]
use crate::*;

// https://rustwasm.github.io/wasm-bindgen/wasm-bindgen-test/usage.html
// the tests must be in the root of the crate, or within a pub mod
use wasm_bindgen_test::*;
// This macro macro is used to indicate that the test is intended to be
// executed in a web browser (and not in other environment; Node.js for example)
wasm_bindgen_test_configure!(run_in_browser);

#[wasm_bindgen_test]
fn protein_alignment() {
    let string_1 = "
    MNFLRRRLSDSSFMANLPNGYMTDLQRPDSSTSSPASPAMERRHPQPLAASFSSPGSSLF
    SSLSSAMKQAPQATSGLMEPPGPSTPIVQRPRILLVIDDAHTDWSKYFHGKKVNGEIEIR
    VEQAEFSELNLAAYVTGGCMVDMQVVRNGTKVVSRSFKPDFILVRQHAYSMALGEDYRSL
    VIGLQYGGLPAVNSLYSVYNFCSKPWVFSQLIKIFHSLGPEKFPLVEQTFFPNHKPMVTA
    PHFPVVVKLGHAHAGMGKIKVENQLDFQDITSVVAMAKTYATTEAFIDSKYDIRIQKIGS
    NYKAYMRTSISGNWKANTGSAMLEQVAMTERYRLWVDSCSEMFGGLDICAVKAVHSKDGR
    DYIIEVMDSSMPLIGEHVEEDRQLMADLVVSKMSQLPMPGGTAPSPLRPWAPQIKSAKSP
    GQAQLGPQLGQPQPRPPPQGGPRQAQSPQPQRSGSPSQQRLSPQGQQPLSPQSGSPQQQR
    SPGSPQLSRASSGSSPNQASKPGATLASQPRPPVQGRSTSQQGEESKKPAPPHPHLNKSQ
    SLTNSLSTSDTSQRGTPSEDEAKAETIRNLRKSFASLFSD";

    let string_2 = "
    MNFSSFKSSFTSNVNFLKRRFSSGDLSSEVDDVDPNSLPPAARPIQDQPTKPPVAGGPPN
    MPPPPAPGQPAGAAPELSLSFGAGKTPATAAPAPPRGVSAPTSPAKSRESLLQRVQSLTG
    AARDQGASILGAAVQSATQRAPAFSKDKYFTLLVLDDQNTDWSKYFRGRRLHGDFDIRVE
    QAEFRDITVVSSADTGPVVTMAAYRSGTRVARSFRPDFVLIRQPPRDGSSDYRSTILGLK
    YGGVPSINSLHSIYQFQDKPWVFSHLLQLQRRLGRDGFPLIEQTFFPNPRDLFQFTKFPS
    VLKAGHCHGGVATARLENQSALQDAAGLVSGAGNDSHCYCTIEPYIDAKFSVHIQKIGNN
    YKAFMRKSITGNWKTNQGSAMLEQITLTEKYKSWVDEISELFGGMEVCGLSVVVAKDGRE
    YIISACDSTFALIGDTQEEDRRQIADLVSGRMQNVCRPSMAQTGPGKLPSRSSVSSRAES
    PTDEGVAPTPPLPAGPRPAPMGGPPPIPERTSPAVGSIGRLSSRSSISEVPEEPSSSGPS
    TVGGVRRDSQTSQSSTISSSVSRAGQRPPQTQNSVVEDAEDTMKNLRKTFAGIFGDM";

    let output = do_protein_alignment(string_1, string_2, 10.0, 0.5, 1, 1);
    assert!(output.is_ok())
}
