//! Data structures storing amino acid substitution matrices

use crate::bioseq::Aac;

const fn map_aminoacid_to_index(code_1: Aac, code_2: Aac) -> u8 {
    match code_1 {
        Aac::A => match code_2 {
            Aac::A => b'\x00',
            Aac::C => b'\x01',
            Aac::D => b'\x02',
            Aac::E => b'\x03',
            Aac::F => b'\x04',
            Aac::G => b'\x05',
            Aac::H => b'\x06',
            Aac::I => b'\x07',
            Aac::K => b'\x08',
            Aac::L => b'\t',
            Aac::M => b'\n',
            Aac::N => b'\x0b',
            Aac::P => b'\x0c',
            Aac::Q => b'\r',
            Aac::R => b'\x0e',
            Aac::S => b'\x0f',
            Aac::T => b'\x10',
            Aac::V => b'\x11',
            Aac::W => b'\x12',
            Aac::Y => b'\x13',
        },
        Aac::C => match code_2 {
            Aac::A => b'\x01',
            Aac::C => b'\x14',
            Aac::D => b'\x15',
            Aac::E => b'\x16',
            Aac::F => b'\x17',
            Aac::G => b'\x18',
            Aac::H => b'\x19',
            Aac::I => b'\x1a',
            Aac::K => b'\x1b',
            Aac::L => b'\x1c',
            Aac::M => b'\x1d',
            Aac::N => b'\x1e',
            Aac::P => b'\x1f',
            Aac::Q => b' ',
            Aac::R => b'!',
            Aac::S => b'"',
            Aac::T => b'#',
            Aac::V => b'$',
            Aac::W => b'%',
            Aac::Y => b'&',
        },
        Aac::D => match code_2 {
            Aac::A => b'\x02',
            Aac::C => b'\x15',
            Aac::D => b'\'',
            Aac::E => b'(',
            Aac::F => b')',
            Aac::G => b'*',
            Aac::H => b'+',
            Aac::I => b',',
            Aac::K => b'-',
            Aac::L => b'.',
            Aac::M => b'/',
            Aac::N => b'0',
            Aac::P => b'1',
            Aac::Q => b'2',
            Aac::R => b'3',
            Aac::S => b'4',
            Aac::T => b'5',
            Aac::V => b'6',
            Aac::W => b'7',
            Aac::Y => b'8',
        },
        Aac::E => match code_2 {
            Aac::A => b'\x03',
            Aac::C => b'\x16',
            Aac::D => b'(',
            Aac::E => b'9',
            Aac::F => b':',
            Aac::G => b';',
            Aac::H => b'<',
            Aac::I => b'=',
            Aac::K => b'>',
            Aac::L => b'?',
            Aac::M => b'@',
            Aac::N => b'A',
            Aac::P => b'B',
            Aac::Q => b'C',
            Aac::R => b'D',
            Aac::S => b'E',
            Aac::T => b'F',
            Aac::V => b'G',
            Aac::W => b'H',
            Aac::Y => b'I',
        },
        Aac::F => match code_2 {
            Aac::A => b'\x04',
            Aac::C => b'\x17',
            Aac::D => b')',
            Aac::E => b':',
            Aac::F => b'J',
            Aac::G => b'K',
            Aac::H => b'L',
            Aac::I => b'M',
            Aac::K => b'N',
            Aac::L => b'O',
            Aac::M => b'P',
            Aac::N => b'Q',
            Aac::P => b'R',
            Aac::Q => b'S',
            Aac::R => b'T',
            Aac::S => b'U',
            Aac::T => b'V',
            Aac::V => b'W',
            Aac::W => b'X',
            Aac::Y => b'Y',
        },
        Aac::G => match code_2 {
            Aac::A => b'\x05',
            Aac::C => b'\x18',
            Aac::D => b'*',
            Aac::E => b';',
            Aac::F => b'K',
            Aac::G => b'Z',
            Aac::H => b'[',
            Aac::I => b'\\',
            Aac::K => b']',
            Aac::L => b'^',
            Aac::M => b'_',
            Aac::N => b'`',
            Aac::P => b'a',
            Aac::Q => b'b',
            Aac::R => b'c',
            Aac::S => b'd',
            Aac::T => b'e',
            Aac::V => b'f',
            Aac::W => b'g',
            Aac::Y => b'h',
        },
        Aac::H => match code_2 {
            Aac::A => b'\x06',
            Aac::C => b'\x19',
            Aac::D => b'+',
            Aac::E => b'<',
            Aac::F => b'L',
            Aac::G => b'[',
            Aac::H => b'i',
            Aac::I => b'j',
            Aac::K => b'k',
            Aac::L => b'l',
            Aac::M => b'm',
            Aac::N => b'n',
            Aac::P => b'o',
            Aac::Q => b'p',
            Aac::R => b'q',
            Aac::S => b'r',
            Aac::T => b's',
            Aac::V => b't',
            Aac::W => b'u',
            Aac::Y => b'v',
        },
        Aac::I => match code_2 {
            Aac::A => b'\x07',
            Aac::C => b'\x1a',
            Aac::D => b',',
            Aac::E => b'=',
            Aac::F => b'M',
            Aac::G => b'\\',
            Aac::H => b'j',
            Aac::I => b'w',
            Aac::K => b'x',
            Aac::L => b'y',
            Aac::M => b'z',
            Aac::N => b'{',
            Aac::P => b'|',
            Aac::Q => b'}',
            Aac::R => b'~',
            Aac::S => b'\x7f',
            Aac::T => b'\x80',
            Aac::V => b'\x81',
            Aac::W => b'\x82',
            Aac::Y => b'\x83',
        },
        Aac::K => match code_2 {
            Aac::A => b'\x08',
            Aac::C => b'\x1b',
            Aac::D => b'-',
            Aac::E => b'>',
            Aac::F => b'N',
            Aac::G => b']',
            Aac::H => b'k',
            Aac::I => b'x',
            Aac::K => b'\x84',
            Aac::L => b'\x85',
            Aac::M => b'\x86',
            Aac::N => b'\x87',
            Aac::P => b'\x88',
            Aac::Q => b'\x89',
            Aac::R => b'\x8a',
            Aac::S => b'\x8b',
            Aac::T => b'\x8c',
            Aac::V => b'\x8d',
            Aac::W => b'\x8e',
            Aac::Y => b'\x8f',
        },
        Aac::L => match code_2 {
            Aac::A => b'\t',
            Aac::C => b'\x1c',
            Aac::D => b'.',
            Aac::E => b'?',
            Aac::F => b'O',
            Aac::G => b'^',
            Aac::H => b'l',
            Aac::I => b'y',
            Aac::K => b'\x85',
            Aac::L => b'\x90',
            Aac::M => b'\x91',
            Aac::N => b'\x92',
            Aac::P => b'\x93',
            Aac::Q => b'\x94',
            Aac::R => b'\x95',
            Aac::S => b'\x96',
            Aac::T => b'\x97',
            Aac::V => b'\x98',
            Aac::W => b'\x99',
            Aac::Y => b'\x9a',
        },
        Aac::M => match code_2 {
            Aac::A => b'\n',
            Aac::C => b'\x1d',
            Aac::D => b'/',
            Aac::E => b'@',
            Aac::F => b'P',
            Aac::G => b'_',
            Aac::H => b'm',
            Aac::I => b'z',
            Aac::K => b'\x86',
            Aac::L => b'\x91',
            Aac::M => b'\x9b',
            Aac::N => b'\x9c',
            Aac::P => b'\x9d',
            Aac::Q => b'\x9e',
            Aac::R => b'\x9f',
            Aac::S => b'\xa0',
            Aac::T => b'\xa1',
            Aac::V => b'\xa2',
            Aac::W => b'\xa3',
            Aac::Y => b'\xa4',
        },
        Aac::N => match code_2 {
            Aac::A => b'\x0b',
            Aac::C => b'\x1e',
            Aac::D => b'0',
            Aac::E => b'A',
            Aac::F => b'Q',
            Aac::G => b'`',
            Aac::H => b'n',
            Aac::I => b'{',
            Aac::K => b'\x87',
            Aac::L => b'\x92',
            Aac::M => b'\x9c',
            Aac::N => b'\xa5',
            Aac::P => b'\xa6',
            Aac::Q => b'\xa7',
            Aac::R => b'\xa8',
            Aac::S => b'\xa9',
            Aac::T => b'\xaa',
            Aac::V => b'\xab',
            Aac::W => b'\xac',
            Aac::Y => b'\xad',
        },
        Aac::P => match code_2 {
            Aac::A => b'\x0c',
            Aac::C => b'\x1f',
            Aac::D => b'1',
            Aac::E => b'B',
            Aac::F => b'R',
            Aac::G => b'a',
            Aac::H => b'o',
            Aac::I => b'|',
            Aac::K => b'\x88',
            Aac::L => b'\x93',
            Aac::M => b'\x9d',
            Aac::N => b'\xa6',
            Aac::P => b'\xae',
            Aac::Q => b'\xaf',
            Aac::R => b'\xb0',
            Aac::S => b'\xb1',
            Aac::T => b'\xb2',
            Aac::V => b'\xb3',
            Aac::W => b'\xb4',
            Aac::Y => b'\xb5',
        },
        Aac::Q => match code_2 {
            Aac::A => b'\r',
            Aac::C => b' ',
            Aac::D => b'2',
            Aac::E => b'C',
            Aac::F => b'S',
            Aac::G => b'b',
            Aac::H => b'p',
            Aac::I => b'}',
            Aac::K => b'\x89',
            Aac::L => b'\x94',
            Aac::M => b'\x9e',
            Aac::N => b'\xa7',
            Aac::P => b'\xaf',
            Aac::Q => b'\xb6',
            Aac::R => b'\xb7',
            Aac::S => b'\xb8',
            Aac::T => b'\xb9',
            Aac::V => b'\xba',
            Aac::W => b'\xbb',
            Aac::Y => b'\xbc',
        },
        Aac::R => match code_2 {
            Aac::A => b'\x0e',
            Aac::C => b'!',
            Aac::D => b'3',
            Aac::E => b'D',
            Aac::F => b'T',
            Aac::G => b'c',
            Aac::H => b'q',
            Aac::I => b'~',
            Aac::K => b'\x8a',
            Aac::L => b'\x95',
            Aac::M => b'\x9f',
            Aac::N => b'\xa8',
            Aac::P => b'\xb0',
            Aac::Q => b'\xb7',
            Aac::R => b'\xbd',
            Aac::S => b'\xbe',
            Aac::T => b'\xbf',
            Aac::V => b'\xc0',
            Aac::W => b'\xc1',
            Aac::Y => b'\xc2',
        },
        Aac::S => match code_2 {
            Aac::A => b'\x0f',
            Aac::C => b'"',
            Aac::D => b'4',
            Aac::E => b'E',
            Aac::F => b'U',
            Aac::G => b'd',
            Aac::H => b'r',
            Aac::I => b'\x7f',
            Aac::K => b'\x8b',
            Aac::L => b'\x96',
            Aac::M => b'\xa0',
            Aac::N => b'\xa9',
            Aac::P => b'\xb1',
            Aac::Q => b'\xb8',
            Aac::R => b'\xbe',
            Aac::S => b'\xc3',
            Aac::T => b'\xc4',
            Aac::V => b'\xc5',
            Aac::W => b'\xc6',
            Aac::Y => b'\xc7',
        },
        Aac::T => match code_2 {
            Aac::A => b'\x10',
            Aac::C => b'#',
            Aac::D => b'5',
            Aac::E => b'F',
            Aac::F => b'V',
            Aac::G => b'e',
            Aac::H => b's',
            Aac::I => b'\x80',
            Aac::K => b'\x8c',
            Aac::L => b'\x97',
            Aac::M => b'\xa1',
            Aac::N => b'\xaa',
            Aac::P => b'\xb2',
            Aac::Q => b'\xb9',
            Aac::R => b'\xbf',
            Aac::S => b'\xc4',
            Aac::T => b'\xc8',
            Aac::V => b'\xc9',
            Aac::W => b'\xca',
            Aac::Y => b'\xcb',
        },
        Aac::V => match code_2 {
            Aac::A => b'\x11',
            Aac::C => b'$',
            Aac::D => b'6',
            Aac::E => b'G',
            Aac::F => b'W',
            Aac::G => b'f',
            Aac::H => b't',
            Aac::I => b'\x81',
            Aac::K => b'\x8d',
            Aac::L => b'\x98',
            Aac::M => b'\xa2',
            Aac::N => b'\xab',
            Aac::P => b'\xb3',
            Aac::Q => b'\xba',
            Aac::R => b'\xc0',
            Aac::S => b'\xc5',
            Aac::T => b'\xc9',
            Aac::V => b'\xcc',
            Aac::W => b'\xcd',
            Aac::Y => b'\xce',
        },
        Aac::W => match code_2 {
            Aac::A => b'\x12',
            Aac::C => b'%',
            Aac::D => b'7',
            Aac::E => b'H',
            Aac::F => b'X',
            Aac::G => b'g',
            Aac::H => b'u',
            Aac::I => b'\x82',
            Aac::K => b'\x8e',
            Aac::L => b'\x99',
            Aac::M => b'\xa3',
            Aac::N => b'\xac',
            Aac::P => b'\xb4',
            Aac::Q => b'\xbb',
            Aac::R => b'\xc1',
            Aac::S => b'\xc6',
            Aac::T => b'\xca',
            Aac::V => b'\xcd',
            Aac::W => b'\xcf',
            Aac::Y => b'\xd0',
        },
        Aac::Y => match code_2 {
            Aac::A => b'\x13',
            Aac::C => b'&',
            Aac::D => b'8',
            Aac::E => b'I',
            Aac::F => b'Y',
            Aac::G => b'h',
            Aac::H => b'v',
            Aac::I => b'\x83',
            Aac::K => b'\x8f',
            Aac::L => b'\x9a',
            Aac::M => b'\xa4',
            Aac::N => b'\xad',
            Aac::P => b'\xb5',
            Aac::Q => b'\xbc',
            Aac::R => b'\xc2',
            Aac::S => b'\xc7',
            Aac::T => b'\xcb',
            Aac::V => b'\xce',
            Aac::W => b'\xd0',
            Aac::Y => b'\xd1',
        },
    }
}

/// Get BLOSUM 62 scores
pub const fn read_blosum62(code_1: Aac, code_2: Aac) -> i8 {
    let index = map_aminoacid_to_index(code_1, code_2);
    match index {
        b'\x00' => 4,
        b'\x01' => 0,
        b'\x02' => -2,
        b'\x03' => -1,
        b'\x04' => -2,
        b'\x05' => 0,
        b'\x06' => -2,
        b'\x07' => -1,
        b'\x08' => -1,
        b'\t' => -1,
        b'\n' => -1,
        b'\x0b' => -2,
        b'\x0c' => -1,
        b'\r' => -1,
        b'\x0e' => -1,
        b'\x0f' => 1,
        b'\x10' => 0,
        b'\x11' => 0,
        b'\x12' => -3,
        b'\x13' => -2,
        b'\x14' => 9,
        b'\x15' => -3,
        b'\x16' => -4,
        b'\x17' => -2,
        b'\x18' => -3,
        b'\x19' => -3,
        b'\x1a' => -1,
        b'\x1b' => -3,
        b'\x1c' => -1,
        b'\x1d' => -1,
        b'\x1e' => -3,
        b'\x1f' => -3,
        b' ' => -3,
        b'!' => -3,
        b'"' => -1,
        b'#' => -1,
        b'$' => -1,
        b'%' => -2,
        b'&' => -2,
        b'\'' => 6,
        b'(' => 2,
        b')' => -3,
        b'*' => -1,
        b'+' => -1,
        b',' => -3,
        b'-' => -1,
        b'.' => -4,
        b'/' => -3,
        b'0' => 1,
        b'1' => -1,
        b'2' => 0,
        b'3' => -2,
        b'4' => 0,
        b'5' => -1,
        b'6' => -3,
        b'7' => -4,
        b'8' => -3,
        b'9' => 5,
        b':' => -3,
        b';' => -2,
        b'<' => 0,
        b'=' => -3,
        b'>' => 1,
        b'?' => -3,
        b'@' => -2,
        b'A' => 0,
        b'B' => -1,
        b'C' => 2,
        b'D' => 0,
        b'E' => 0,
        b'F' => -1,
        b'G' => -2,
        b'H' => -3,
        b'I' => -2,
        b'J' => 6,
        b'K' => -3,
        b'L' => -1,
        b'M' => 0,
        b'N' => -3,
        b'O' => 0,
        b'P' => 0,
        b'Q' => -3,
        b'R' => -4,
        b'S' => -3,
        b'T' => -3,
        b'U' => -2,
        b'V' => -2,
        b'W' => -1,
        b'X' => 1,
        b'Y' => 3,
        b'Z' => 6,
        b'[' => -2,
        b'\\' => -4,
        b']' => -2,
        b'^' => -4,
        b'_' => -3,
        b'`' => 0,
        b'a' => -2,
        b'b' => -2,
        b'c' => -2,
        b'd' => 0,
        b'e' => -2,
        b'f' => -3,
        b'g' => -2,
        b'h' => -3,
        b'i' => 8,
        b'j' => -3,
        b'k' => -1,
        b'l' => -3,
        b'm' => -2,
        b'n' => 1,
        b'o' => -2,
        b'p' => 0,
        b'q' => 0,
        b'r' => -1,
        b's' => -2,
        b't' => -3,
        b'u' => -2,
        b'v' => 2,
        b'w' => 4,
        b'x' => -3,
        b'y' => 2,
        b'z' => 1,
        b'{' => -3,
        b'|' => -3,
        b'}' => -3,
        b'~' => -3,
        b'\x7f' => -2,
        b'\x80' => -1,
        b'\x81' => 3,
        b'\x82' => -3,
        b'\x83' => -1,
        b'\x84' => 5,
        b'\x85' => -2,
        b'\x86' => -1,
        b'\x87' => 0,
        b'\x88' => -1,
        b'\x89' => 1,
        b'\x8a' => 2,
        b'\x8b' => 0,
        b'\x8c' => -1,
        b'\x8d' => -2,
        b'\x8e' => -3,
        b'\x8f' => -2,
        b'\x90' => 4,
        b'\x91' => 2,
        b'\x92' => -3,
        b'\x93' => -3,
        b'\x94' => -2,
        b'\x95' => -2,
        b'\x96' => -2,
        b'\x97' => -1,
        b'\x98' => 1,
        b'\x99' => -2,
        b'\x9a' => -1,
        b'\x9b' => 5,
        b'\x9c' => -2,
        b'\x9d' => -2,
        b'\x9e' => 0,
        b'\x9f' => -1,
        b'\xa0' => -1,
        b'\xa1' => -1,
        b'\xa2' => 1,
        b'\xa3' => -1,
        b'\xa4' => -1,
        b'\xa5' => 6,
        b'\xa6' => -2,
        b'\xa7' => 0,
        b'\xa8' => 0,
        b'\xa9' => 1,
        b'\xaa' => 0,
        b'\xab' => -3,
        b'\xac' => -4,
        b'\xad' => -2,
        b'\xae' => 7,
        b'\xaf' => -1,
        b'\xb0' => -2,
        b'\xb1' => -1,
        b'\xb2' => -1,
        b'\xb3' => -2,
        b'\xb4' => -4,
        b'\xb5' => -3,
        b'\xb6' => 5,
        b'\xb7' => 1,
        b'\xb8' => 0,
        b'\xb9' => -1,
        b'\xba' => -2,
        b'\xbb' => -2,
        b'\xbc' => -1,
        b'\xbd' => 5,
        b'\xbe' => -1,
        b'\xbf' => -1,
        b'\xc0' => -3,
        b'\xc1' => -3,
        b'\xc2' => -2,
        b'\xc3' => 4,
        b'\xc4' => 1,
        b'\xc5' => -2,
        b'\xc6' => -3,
        b'\xc7' => -2,
        b'\xc8' => 5,
        b'\xc9' => 0,
        b'\xca' => -2,
        b'\xcb' => -2,
        b'\xcc' => 4,
        b'\xcd' => -3,
        b'\xce' => -1,
        b'\xcf' => 11,
        b'\xd0' => 2,
        b'\xd1' => 7,
        _ => panic!("Code not found. The table may be incomplete."),
    }
}

/// Get BLOSUM 45 scores
pub const fn read_blosum45(code_1: Aac, code_2: Aac) -> i8 {
    let index = map_aminoacid_to_index(code_1, code_2);

    match index {
        b'\x00' => 5,
        b'\x01' => -1,
        b'\x02' => -2,
        b'\x03' => -1,
        b'\x04' => -2,
        b'\x05' => 0,
        b'\x06' => -2,
        b'\x07' => -1,
        b'\x08' => -1,
        b'\t' => -1,
        b'\n' => -1,
        b'\x0b' => -1,
        b'\x0c' => -1,
        b'\r' => -1,
        b'\x0e' => -2,
        b'\x0f' => 1,
        b'\x10' => 0,
        b'\x11' => 0,
        b'\x12' => -2,
        b'\x13' => -2,
        b'\x14' => 12,
        b'\x15' => -3,
        b'\x16' => -3,
        b'\x17' => -2,
        b'\x18' => -3,
        b'\x19' => -3,
        b'\x1a' => -3,
        b'\x1b' => -3,
        b'\x1c' => -2,
        b'\x1d' => -2,
        b'\x1e' => -2,
        b'\x1f' => -4,
        b' ' => -3,
        b'!' => -3,
        b'"' => -1,
        b'#' => -1,
        b'$' => -1,
        b'%' => -5,
        b'&' => -3,
        b'\'' => 7,
        b'(' => 2,
        b')' => -4,
        b'*' => -1,
        b'+' => 0,
        b',' => -4,
        b'-' => 0,
        b'.' => -3,
        b'/' => -3,
        b'0' => 2,
        b'1' => -1,
        b'2' => 0,
        b'3' => -1,
        b'4' => 0,
        b'5' => -1,
        b'6' => -3,
        b'7' => -4,
        b'8' => -2,
        b'9' => 6,
        b':' => -3,
        b';' => -2,
        b'<' => 0,
        b'=' => -3,
        b'>' => 1,
        b'?' => -2,
        b'@' => -2,
        b'A' => 0,
        b'B' => 0,
        b'C' => 2,
        b'D' => 0,
        b'E' => 0,
        b'F' => -1,
        b'G' => -3,
        b'H' => -3,
        b'I' => -2,
        b'J' => 8,
        b'K' => -3,
        b'L' => -2,
        b'M' => 0,
        b'N' => -3,
        b'O' => 1,
        b'P' => 0,
        b'Q' => -2,
        b'R' => -3,
        b'S' => -4,
        b'T' => -2,
        b'U' => -2,
        b'V' => -1,
        b'W' => 0,
        b'X' => 1,
        b'Y' => 3,
        b'Z' => 7,
        b'[' => -2,
        b'\\' => -4,
        b']' => -2,
        b'^' => -3,
        b'_' => -2,
        b'`' => 0,
        b'a' => -2,
        b'b' => -2,
        b'c' => -2,
        b'd' => 0,
        b'e' => -2,
        b'f' => -3,
        b'g' => -2,
        b'h' => -3,
        b'i' => 10,
        b'j' => -3,
        b'k' => -1,
        b'l' => -2,
        b'm' => 0,
        b'n' => 1,
        b'o' => -2,
        b'p' => 1,
        b'q' => 0,
        b'r' => -1,
        b's' => -2,
        b't' => -3,
        b'u' => -3,
        b'v' => 2,
        b'w' => 5,
        b'x' => -3,
        b'y' => 2,
        b'z' => 2,
        b'{' => -2,
        b'|' => -2,
        b'}' => -2,
        b'~' => -3,
        b'\x7f' => -2,
        b'\x80' => -1,
        b'\x81' => 3,
        b'\x82' => -2,
        b'\x83' => 0,
        b'\x84' => 5,
        b'\x85' => -3,
        b'\x86' => -1,
        b'\x87' => 0,
        b'\x88' => -1,
        b'\x89' => 1,
        b'\x8a' => 3,
        b'\x8b' => -1,
        b'\x8c' => -1,
        b'\x8d' => -2,
        b'\x8e' => -2,
        b'\x8f' => -1,
        b'\x90' => 5,
        b'\x91' => 2,
        b'\x92' => -3,
        b'\x93' => -3,
        b'\x94' => -2,
        b'\x95' => -2,
        b'\x96' => -3,
        b'\x97' => -1,
        b'\x98' => 1,
        b'\x99' => -2,
        b'\x9a' => 0,
        b'\x9b' => 6,
        b'\x9c' => -2,
        b'\x9d' => -2,
        b'\x9e' => 0,
        b'\x9f' => -1,
        b'\xa0' => -2,
        b'\xa1' => -1,
        b'\xa2' => 1,
        b'\xa3' => -2,
        b'\xa4' => 0,
        b'\xa5' => 6,
        b'\xa6' => -2,
        b'\xa7' => 0,
        b'\xa8' => 0,
        b'\xa9' => 1,
        b'\xaa' => 0,
        b'\xab' => -3,
        b'\xac' => -4,
        b'\xad' => -2,
        b'\xae' => 9,
        b'\xaf' => -1,
        b'\xb0' => -2,
        b'\xb1' => -1,
        b'\xb2' => -1,
        b'\xb3' => -3,
        b'\xb4' => -3,
        b'\xb5' => -3,
        b'\xb6' => 6,
        b'\xb7' => 1,
        b'\xb8' => 0,
        b'\xb9' => -1,
        b'\xba' => -3,
        b'\xbb' => -2,
        b'\xbc' => -1,
        b'\xbd' => 7,
        b'\xbe' => -1,
        b'\xbf' => -1,
        b'\xc0' => -2,
        b'\xc1' => -2,
        b'\xc2' => -1,
        b'\xc3' => 4,
        b'\xc4' => 2,
        b'\xc5' => -1,
        b'\xc6' => -4,
        b'\xc7' => -2,
        b'\xc8' => 5,
        b'\xc9' => 0,
        b'\xca' => -3,
        b'\xcb' => -1,
        b'\xcc' => 5,
        b'\xcd' => -3,
        b'\xce' => -1,
        b'\xcf' => 15,
        b'\xd0' => 3,
        b'\xd1' => 8,
        _ => panic!("Code not found. The table may be incomplete."),
    }
}

/// Get PAM 160 scores
pub const fn read_pam160(code_1: Aac, code_2: Aac) -> i8 {
    let index = map_aminoacid_to_index(code_1, code_2);
    match index {
        b'\x00' => 2,
        b'\x01' => -2,
        b'\x02' => 0,
        b'\x03' => 0,
        b'\x04' => -3,
        b'\x05' => 1,
        b'\x06' => -2,
        b'\x07' => -1,
        b'\x08' => -2,
        b'\t' => -2,
        b'\n' => -1,
        b'\x0b' => 0,
        b'\x0c' => 1,
        b'\r' => -1,
        b'\x0e' => -2,
        b'\x0f' => 1,
        b'\x10' => 1,
        b'\x11' => 0,
        b'\x12' => -5,
        b'\x13' => -3,
        b'\x14' => 9,
        b'\x15' => -5,
        b'\x16' => -5,
        b'\x17' => -5,
        b'\x18' => -3,
        b'\x19' => -3,
        b'\x1a' => -2,
        b'\x1b' => -5,
        b'\x1c' => -6,
        b'\x1d' => -5,
        b'\x1e' => -4,
        b'\x1f' => -3,
        b' ' => -5,
        b'!' => -3,
        b'"' => 0,
        b'#' => -2,
        b'$' => -2,
        b'%' => -7,
        b'&' => 0,
        b'\'' => 4,
        b'(' => 3,
        b')' => -6,
        b'*' => 0,
        b'+' => 0,
        b',' => -3,
        b'-' => 0,
        b'.' => -4,
        b'/' => -3,
        b'0' => 2,
        b'1' => -2,
        b'2' => 1,
        b'3' => -2,
        b'4' => 0,
        b'5' => -1,
        b'6' => -3,
        b'7' => -6,
        b'8' => -4,
        b'9' => 4,
        b':' => -5,
        b';' => 0,
        b'<' => 0,
        b'=' => -2,
        b'>' => -1,
        b'?' => -3,
        b'@' => -2,
        b'A' => 1,
        b'B' => -1,
        b'C' => 2,
        b'D' => -2,
        b'E' => 0,
        b'F' => -1,
        b'G' => -2,
        b'H' => -7,
        b'I' => -4,
        b'J' => 7,
        b'K' => -4,
        b'L' => -2,
        b'M' => 0,
        b'N' => -5,
        b'O' => 1,
        b'P' => 0,
        b'Q' => -3,
        b'R' => -4,
        b'S' => -5,
        b'T' => -4,
        b'U' => -3,
        b'V' => -3,
        b'W' => -2,
        b'X' => -1,
        b'Y' => 5,
        b'Z' => 4,
        b'[' => -3,
        b'\\' => -3,
        b']' => -2,
        b'^' => -4,
        b'_' => -3,
        b'`' => 0,
        b'a' => -1,
        b'b' => -2,
        b'c' => -3,
        b'd' => 1,
        b'e' => -1,
        b'f' => -2,
        b'g' => -7,
        b'h' => -5,
        b'i' => 6,
        b'j' => -3,
        b'k' => -1,
        b'l' => -2,
        b'm' => -3,
        b'n' => 2,
        b'o' => -1,
        b'p' => 2,
        b'q' => 1,
        b'r' => -1,
        b's' => -2,
        b't' => -2,
        b'u' => -3,
        b'v' => 0,
        b'w' => 5,
        b'x' => -2,
        b'y' => 2,
        b'z' => 2,
        b'{' => -2,
        b'|' => -2,
        b'}' => -2,
        b'~' => -2,
        b'\x7f' => -2,
        b'\x80' => 0,
        b'\x81' => 3,
        b'\x82' => -5,
        b'\x83' => -2,
        b'\x84' => 4,
        b'\x85' => -3,
        b'\x86' => 0,
        b'\x87' => 1,
        b'\x88' => -2,
        b'\x89' => 0,
        b'\x8a' => 3,
        b'\x8b' => -1,
        b'\x8c' => 0,
        b'\x8d' => -3,
        b'\x8e' => -4,
        b'\x8f' => -4,
        b'\x90' => 5,
        b'\x91' => 3,
        b'\x92' => -3,
        b'\x93' => -3,
        b'\x94' => -2,
        b'\x95' => -3,
        b'\x96' => -3,
        b'\x97' => -2,
        b'\x98' => 1,
        b'\x99' => -2,
        b'\x9a' => -2,
        b'\x9b' => 7,
        b'\x9c' => -2,
        b'\x9d' => -2,
        b'\x9e' => -1,
        b'\x9f' => -1,
        b'\xa0' => -2,
        b'\xa1' => -1,
        b'\xa2' => 1,
        b'\xa3' => -4,
        b'\xa4' => -3,
        b'\xa5' => 3,
        b'\xa6' => -1,
        b'\xa7' => 0,
        b'\xa8' => -1,
        b'\xa9' => 1,
        b'\xaa' => 0,
        b'\xab' => -2,
        b'\xac' => -4,
        b'\xad' => -2,
        b'\xae' => 5,
        b'\xaf' => 0,
        b'\xb0' => -1,
        b'\xb1' => 1,
        b'\xb2' => 0,
        b'\xb3' => -2,
        b'\xb4' => -5,
        b'\xb5' => -5,
        b'\xb6' => 5,
        b'\xb7' => 1,
        b'\xb8' => -1,
        b'\xb9' => -1,
        b'\xba' => -2,
        b'\xbb' => -5,
        b'\xbc' => -4,
        b'\xbd' => 6,
        b'\xbe' => -1,
        b'\xbf' => -1,
        b'\xc0' => -3,
        b'\xc1' => 1,
        b'\xc2' => -4,
        b'\xc3' => 2,
        b'\xc4' => 1,
        b'\xc5' => -1,
        b'\xc6' => -2,
        b'\xc7' => -3,
        b'\xc8' => 3,
        b'\xc9' => 0,
        b'\xca' => -6,
        b'\xcb' => -3,
        b'\xcc' => 4,
        b'\xcd' => -6,
        b'\xce' => -3,
        b'\xcf' => 12,
        b'\xd0' => -1,
        b'\xd1' => 8,
        _ => panic!("Code not found. The table may be incomplete."),
    }
}

#[cfg(test)]
mod test {
    use super::*;

    const ALL_AAC: [Aac; 20] = [
        Aac::A,
        Aac::C,
        Aac::D,
        Aac::E,
        Aac::F,
        Aac::G,
        Aac::H,
        Aac::I,
        Aac::K,
        Aac::L,
        Aac::M,
        Aac::N,
        Aac::P,
        Aac::Q,
        Aac::R,
        Aac::S,
        Aac::T,
        Aac::V,
        Aac::W,
        Aac::Y,
    ];

    #[test]
    fn check_some_blosum45() {
        let score_cases = [
            // Diagonal extremes and mid
            (5, Aac::A, Aac::A),
            (8, Aac::Y, Aac::Y),
            (6, Aac::N, Aac::N),
            // Check symmetria
            (-2, Aac::P, Aac::I),
            (-2, Aac::I, Aac::P),
            (-2, Aac::Q, Aac::G),
            (-2, Aac::G, Aac::Q),
        ];
        for (expected, code_1, code_2) in score_cases {
            assert_eq!(expected, read_blosum45(code_1, code_2))
        }
    }

    #[test]
    fn blosum45_is_complete() {
        for code_1 in ALL_AAC {
            for code_2 in ALL_AAC {
                read_blosum45(code_1, code_2);
            }
        }
    }

    #[test]
    fn check_some_blosum62() {
        let score_cases = [
            // Diagonal extremes and mid
            (4, Aac::A, Aac::A),
            (7, Aac::Y, Aac::Y),
            (6, Aac::N, Aac::N),
            // Check symmetria
            (-3, Aac::P, Aac::I),
            (-3, Aac::I, Aac::P),
            (-2, Aac::Q, Aac::G),
            (-2, Aac::G, Aac::Q),
        ];

        for (expected, code_1, code_2) in score_cases {
            assert_eq!(expected, read_blosum62(code_1, code_2))
        }
    }

    #[test]
    fn blosum62_is_complete() {
        for code_1 in ALL_AAC {
            for code_2 in ALL_AAC {
                read_blosum62(code_1, code_2);
            }
        }
    }

    #[test]
    fn check_some_pam160() {
        let score_cases = [
            // Diagonal extremes and mid
            (2, Aac::A, Aac::A),
            (8, Aac::Y, Aac::Y),
            (3, Aac::N, Aac::N),
            // Check symmetria
            (-2, Aac::P, Aac::I),
            (-2, Aac::I, Aac::P),
            (-2, Aac::Q, Aac::G),
            (-2, Aac::G, Aac::Q),
        ];

        for (expected, code_1, code_2) in score_cases {
            assert_eq!(expected, read_pam160(code_1, code_2))
        }
    }

    #[test]
    fn paread_pam160_is_complete() {
        for code_1 in ALL_AAC {
            for code_2 in ALL_AAC {
                read_pam160(code_1, code_2);
            }
        }
    }
}
